const players = [
  { rank: 1, name: "Scottie Scheffler" },
  { rank: 2, name: "Xander Schauffele" },
  { rank: 3, name: "Hideki Matsuyama" },
  { rank: 4, name: "Keegan Bradley" },
  { rank: 5, name: "Ludvig Åberg" },
  { rank: 6, name: "Rory McIlroy" },
  { rank: 7, name: "Collin Morikawa" },
  { rank: 8, name: "Wyndham Clark" },
  { rank: 9, name: "Sam Burns" },
  { rank: 10, name: "Patrick Cantlay" },
  { rank: 11, name: "Sungjae Im" },
  { rank: 12, name: "Sahith Theegala" },
  { rank: 13, name: "Shane Lowry" },
  { rank: 14, name: "Adam Scott" },
  { rank: 15, name: "Tony Finau" },
  { rank: 16, name: "Byeong Hun An" },
  { rank: 17, name: "Viktor Hovland" },
  { rank: 18, name: "Russell Henley" },
  { rank: 19, name: "Akshay Bhatia" },
  { rank: 20, name: "Robert MacIntyre" },
  { rank: 21, name: "Billy Horschel" },
  { rank: 22, name: "Tommy Fleetwood" },
  { rank: 23, name: "Sepp Straka" },
  { rank: 24, name: "Matthieu Pavon" },
  { rank: 25, name: "Taylor Pendrith" },
  { rank: 26, name: "Chris Kirk" },
  { rank: 27, name: "Tom Hoge" },
  { rank: 28, name: "Aaron Rai" },
  { rank: 29, name: "Christiaan Bezuidenhout" },
  { rank: 30, name: "Justin Thomas" },
];

export const getPlayers = async () => {
  return players;
};
